"""

Revision ID: 3a2a330288e4
Revises: 63e439b8106e
Create Date: 2024-07-08 02:22:30.416621

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3a2a330288e4'
down_revision = '63e439b8106e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smscoderecord',
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('expire_time', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sms_code', sa.Integer(), nullable=False),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smscoderecord')
    # ### end Alembic commands ###
