"""增加shortID

Revision ID: 68a872d5103d
Revises: 442ba1518712
Create Date: 2025-01-07 17:04:59.698786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '68a872d5103d'
down_revision = '442ba1518712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shortid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_shortid'), 'user', ['shortid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_shortid'), table_name='user')
    op.drop_column('user', 'shortid')
    # ### end Alembic commands ###
