"""增加起卦记录表

Revision ID: 95567daf8ec4
Revises: 7c3eb97206f5
Create Date: 2025-02-23 05:50:47.487360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95567daf8ec4'
down_revision = '7c3eb97206f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
