"""增加起卦记录表

Revision ID: a32039f718ee
Revises: 95567daf8ec4
Create Date: 2025-02-23 05:54:13.405660

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a32039f718ee'
down_revision = '95567daf8ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divinationrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_gua', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_gua', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divinationrecord_id'), 'divinationrecord', ['id'], unique=False)
    op.create_index(op.f('ix_divinationrecord_title'), 'divinationrecord', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divinationrecord_title'), table_name='divinationrecord')
    op.drop_index(op.f('ix_divinationrecord_id'), table_name='divinationrecord')
    op.drop_table('divinationrecord')
    # ### end Alembic commands ###
