""" 起卦标题不唯一

Revision ID: d596ab360d77
Revises: a32039f718ee
Create Date: 2025-02-23 06:22:22.171037

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd596ab360d77'
down_revision = 'a32039f718ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_divinationrecord_title', table_name='divinationrecord')
    op.create_index(op.f('ix_divinationrecord_title'), 'divinationrecord', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divinationrecord_title'), table_name='divinationrecord')
    op.create_index('ix_divinationrecord_title', 'divinationrecord', ['title'], unique=True)
    # ### end Alembic commands ###
